### ISSUE TITLE
Bug: Interferes with NPC Indicators

### ISSUE THREAD

**Issue by darkharasho** [SkyBouncer/sky_slayer#4]
This addon seems to interfere with [NPC Indicators](https://github.com/runelite/runelite/wiki/NPC-Indicators). I can't highlight npcs with this plugin enabled.

Without plugin:
![image](https://github.com/user-attachments/assets/d841a6e6-dfc4-4305-a1a4-5409260b811b)

With plugin:
![image](https://github.com/user-attachments/assets/4c4aef8e-e87d-49b1-89bc-8231f63b1861)

**Comment by iProdigy** [comment]
@kristian-roa @computaskrig are yall aware of this issue? (noticed you didn't have the repo [watched](https://github.com/SkyBouncer/sky_slayer/watchers) on github)
